const MEDS = [
  {
    "id": 1,
    "nombre": "Aciclovir 250 mg Aciclovir 500 mg",
    "categoria": "Antimicrobiano",
    "presentacion": "Aciclovir 250 mg Aciclovir 500 mg",
    "reconstitucion": "Solvente incluido en envase o\nAciclovir 250 mg:10 mL\nAciclovir 500 mg:20 mL \nSF0.9% o SG5%",
    "dilucion": "100 mL SF0.9% o SG5%\nNo exceder 5 mg/mL",
    "administracion": "1 h",
    "estabilidad": "TA: 24 h",
    "ph": "10,5-11,6",
    "osmolaridad": "316 – 3191",
    "riesgo": "Alto",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 5.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: nefrotoxicidad/cristaluria, flebitis y neurotoxicidad (confusión/temblor), sobre todo con función renal alterada. Vigilar hidratación, creatinina y sitio de infusión."
  },
  {
    "id": 2,
    "nombre": "Amikacina 100 mg Amikacina 500 mg",
    "categoria": "Antimicrobiano",
    "presentacion": "Amikacina 100 mg Amikacina 500 mg",
    "reconstitucion": "No requiere solvente",
    "dilucion": "100 - 200 mL\nSF0.9% – SG 5%",
    "administracion": "30-60 min",
    "estabilidad": "TA: 24 h",
    "ph": "3,5-5,5",
    "osmolaridad": "349",
    "riesgo": "Moderado",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 5.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: nefrotoxicidad y ototoxicidad. Vigilar función renal, balance hídrico, audición y niveles plasmáticos si aplica."
  },
  {
    "id": 3,
    "nombre": "Ampicilina 500 mg",
    "categoria": "Antimicrobiano",
    "presentacion": "Ampicilina 500 mg",
    "reconstitucion": "Agua para inyectable\n5 mL para 500 mg",
    "dilucion": "50 mL - 100 mL SF0.9%\nNo exceder 30 mg/mL",
    "administracion": "Bolo: 10- 15 min\nIV: 30-60 min\nNo exceder 100 mg/min",
    "estabilidad": "TA: 8 h",
    "ph": "8-10",
    "osmolaridad": "372- 620",
    "riesgo": "Alto",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 30.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: hipersensibilidad/anafilaxia, rash, diarrea/C. difficile y flebitis. Vigilar antecedentes de alergia beta-lactámica y sitio de infusión."
  },
  {
    "id": 4,
    "nombre": "Ampicilina/sulbactam 1000 mg / 500 mg",
    "categoria": "Antimicrobiano",
    "presentacion": "Ampicilina/sulbactam 1000 mg / 500 mg",
    "reconstitucion": "Agua para inyectable",
    "dilucion": "50 mL - 100 mL\n SF0.9%",
    "administracion": "Bolo: 10- 15 min\nInfusión IV: 15-30 min",
    "estabilidad": "RE: 24 h",
    "ph": "8-10",
    "osmolaridad": "400",
    "riesgo": "Alto",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 30.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: hipersensibilidad/anafilaxia, rash, diarrea/C. difficile y flebitis. Vigilar antecedentes de alergia beta-lactámica y sitio de infusión."
  },
  {
    "id": 5,
    "nombre": "Anfotericina b DESOXICOLATO  50 mg (convencional)",
    "categoria": "Antimicrobiano",
    "presentacion": "Anfotericina b DESOXICOLATO  50 mg (convencional)",
    "reconstitucion": "10 mL \nAgua para inyectable",
    "dilucion": "500 mL SG5%\nVía Periférica: 0,1 mg/mL\nVía Central: 0,25-0,5 mg/mL",
    "administracion": "2-6 h",
    "estabilidad": "Utilizar una vez diluido y proteger de la luz.",
    "ph": "5,0-6,0",
    "osmolaridad": "256",
    "riesgo": "Bajo",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 0.5,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: reacción durante infusión, fiebre/escalofríos, nefrotoxicidad, hipokalemia e hipomagnesemia. Vigilar función renal y electrolitos."
  },
  {
    "id": 6,
    "nombre": "Anfotericina b  50 mg LIPOSOMAL",
    "categoria": "Antimicrobiano",
    "presentacion": "Anfotericina b  50 mg LIPOSOMAL",
    "reconstitucion": "12 mL Agua para inyectable\n(4mg/mL)",
    "dilucion": "25- 250 mL SG5%\n(0,2 – 2 mg/mL)",
    "administracion": "30-60 min",
    "estabilidad": "No disponible",
    "ph": "No disponible",
    "osmolaridad": "280",
    "riesgo": "Bajo",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 2.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: reacción durante infusión, fiebre/escalofríos, nefrotoxicidad, hipokalemia e hipomagnesemia. Vigilar función renal y electrolitos."
  },
  {
    "id": 7,
    "nombre": "Anidulafungina  100 mg",
    "categoria": "Antimicrobiano",
    "presentacion": "Anidulafungina  100 mg",
    "reconstitucion": "30 mL Agua para inyectable",
    "dilucion": "100 mL SG5% o SF 0.9%\nNo exceder 0,77 mg/mL",
    "administracion": "90 min, \nno exceder \n1,1 mg/min",
    "estabilidad": "RE: 24 h",
    "ph": "3,5-5,5",
    "osmolaridad": "No disponible",
    "riesgo": "Bajo",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 0.77,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: reacción relacionada con infusión, rash/prurito, fiebre y alteración de pruebas hepáticas. Vigilar tolerancia durante infusión."
  },
  {
    "id": 8,
    "nombre": "Caspofungina 70 mg Caspofungina 50 mg",
    "categoria": "Antimicrobiano",
    "presentacion": "Caspofungina 70 mg Caspofungina 50 mg",
    "reconstitucion": "10,5 mL Agua para inyectable o SF0.9%",
    "dilucion": "250 mL SF0.9%",
    "administracion": "Infusión IV prolongada durante 60 min",
    "estabilidad": "Reconstitución\nTA: 1 h \nDiluido: 48 h entre 2-8 °C",
    "ph": "6,6",
    "osmolaridad": "309",
    "riesgo": "Bajo",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 0.2,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: reacción relacionada con infusión, rash/prurito, fiebre y alteración de pruebas hepáticas. Vigilar tolerancia durante infusión."
  },
  {
    "id": 9,
    "nombre": "Cefazolina  1 gr",
    "categoria": "Antimicrobiano",
    "presentacion": "Cefazolina  1 gr",
    "reconstitucion": "2,5 mL\n Agua para inyectables",
    "dilucion": "IV Directo: 5 mL SF0.9% SG5%\n50-100 mL SF0.9%, SG5%",
    "administracion": "IV Directo: 5 min\n30-60 min",
    "estabilidad": "TA: 24 h",
    "ph": "4,5-7",
    "osmolaridad": "317-351",
    "riesgo": "Bajo",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 20.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: hipersensibilidad beta-lactámica, rash, diarrea/C. difficile, alteración hepática/hematológica rara. Vigilar alergia y tolerancia digestiva."
  },
  {
    "id": 10,
    "nombre": "Cefepime  1 g",
    "categoria": "Antimicrobiano",
    "presentacion": "Cefepime  1 g",
    "reconstitucion": "10 mL \nAgua para inyectables",
    "dilucion": "50-100 mL \nSF0.9%, SG5%",
    "administracion": "IV: 30 mi",
    "estabilidad": "TA: 12 h \nRE: 24 h",
    "ph": "4-6",
    "osmolaridad": "307",
    "riesgo": "Bajo",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 40.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: alergia beta-lactámica, diarrea/C. difficile y neurotoxicidad (encefalopatía, mioclonías, convulsiones), sobre todo en falla renal. Ajustar dosis."
  },
  {
    "id": 11,
    "nombre": "Cefotaxima  1g",
    "categoria": "Antimicrobiano",
    "presentacion": "Cefotaxima  1g",
    "reconstitucion": "4 mL \nAgua para inyectables",
    "dilucion": "50 mL– 100 mL\nSF0.9%, SG5%",
    "administracion": "IV:15-60 min",
    "estabilidad": "TA: 24 h\nRE: 7-10 días",
    "ph": "5-7,5",
    "osmolaridad": "344-357",
    "riesgo": "Bajo",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 20.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: hipersensibilidad beta-lactámica, rash, diarrea/C. difficile, alteración hepática/hematológica rara. Vigilar alergia y tolerancia digestiva."
  },
  {
    "id": 12,
    "nombre": "Ceftazidima  1 g",
    "categoria": "Antimicrobiano",
    "presentacion": "Ceftazidima  1 g",
    "reconstitucion": "10 mL \nAgua para inyectables",
    "dilucion": "25 -100 mL \nSF0.9%, SG5%",
    "administracion": "IV :30-60 min",
    "estabilidad": "TA: 24 h\nRE: 7 días",
    "ph": "5 -8",
    "osmolaridad": "240-330",
    "riesgo": "Bajo",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 40.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: hipersensibilidad beta-lactámica, rash, diarrea/C. difficile, alteración hepática/hematológica rara. Vigilar alergia y tolerancia digestiva."
  },
  {
    "id": 13,
    "nombre": "Ceftazidima/Avibactam 2 g /0.5 g",
    "categoria": "Antimicrobiano",
    "presentacion": "Ceftazidima/Avibactam 2 g /0.5 g",
    "reconstitucion": "10 mL\n Agua para inyectables",
    "dilucion": "50-250 mL \nSF0.9%, SG5%",
    "administracion": "IV:120 min",
    "estabilidad": "TA: 30 min",
    "ph": "6.73",
    "osmolaridad": "386",
    "riesgo": "Bajo",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 50.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: hipersensibilidad beta-lactámica, rash, diarrea/C. difficile, alteración hepática/hematológica rara. Vigilar alergia y tolerancia digestiva."
  },
  {
    "id": 14,
    "nombre": "Ceftriaxona  1g",
    "categoria": "Antimicrobiano",
    "presentacion": "Ceftriaxona  1g",
    "reconstitucion": "10 mL \nAgua para inyectables",
    "dilucion": "25-100 mL SF0.9%, SG5%\n(no exceder los 40mg/mL)",
    "administracion": "IV: 30 min",
    "estabilidad": "TA: 24 h",
    "ph": "6,6-6,7",
    "osmolaridad": "350",
    "riesgo": "Bajo",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 40.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: hipersensibilidad beta-lactámica, rash, diarrea/C. difficile, alteración hepática/hematológica rara. Vigilar alergia y tolerancia digestiva."
  },
  {
    "id": 15,
    "nombre": "Ciprofloxacino  200 mg",
    "categoria": "Antimicrobiano",
    "presentacion": "Ciprofloxacino  200 mg",
    "reconstitucion": "No procede",
    "dilucion": "No procede",
    "administracion": "IV 200 mg: 60 min\nIV 400 mg: 120 min",
    "estabilidad": "No disponible",
    "ph": "3,3-4,6",
    "osmolaridad": "285",
    "riesgo": "Moderado",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": null,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: prolongación QT, tendinopatía/ruptura tendinosa, alteraciones SNC, disglucemias y flebitis. Precaución en adulto mayor y falla renal."
  },
  {
    "id": 16,
    "nombre": "Clindamicina  600 mg",
    "categoria": "Antimicrobiano",
    "presentacion": "Clindamicina  600 mg",
    "reconstitucion": "No procede",
    "dilucion": "300 mg - 600 mg en 50 mL\n 900 mg: 50-100 mL\n 1200 mg: 100 mL\nSG5%",
    "administracion": "IV:\n300 mg:10 min\n600 mg:20 min\n900 mg: 30 min \n1200 mg: 60 min\nNo exceder 30 mg/min",
    "estabilidad": "TA: 24 h",
    "ph": "6,3\n (5,5 - 7,0)",
    "osmolaridad": "294",
    "riesgo": "Bajo",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 18.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: diarrea y colitis por Clostridioides difficile, rash y hepatotoxicidad rara. Vigilar diarrea durante y después del tratamiento."
  },
  {
    "id": 17,
    "nombre": "Cloxacilina  500 mg",
    "categoria": "Antimicrobiano",
    "presentacion": "Cloxacilina  500 mg",
    "reconstitucion": "10 mL\n Agua para inyectables",
    "dilucion": "50-100 mL \nSG5%, SF0.9%",
    "administracion": "Bolo durante 3-5 min\n IV: 30-60 min",
    "estabilidad": "Administrar\nInmediatamente",
    "ph": "8-10",
    "osmolaridad": "368",
    "riesgo": "Moderado",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 10.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: hipersensibilidad/anafilaxia, rash, diarrea/C. difficile y flebitis. Vigilar antecedentes de alergia beta-lactámica y sitio de infusión."
  },
  {
    "id": 18,
    "nombre": "COLISTIN  Colistimetato de sodio  240 mg = 100 mg Colistin 3 millones UI de colistina base",
    "categoria": "Antimicrobiano",
    "presentacion": "COLISTIN  Colistimetato de sodio  240 mg = 100 mg Colistin 3 millones UI de colistina base",
    "reconstitucion": "2 mL \nAgua para inyectables",
    "dilucion": "100 mL\nSF0.9%, SG5%",
    "administracion": "IV: 30 min - 1 hora",
    "estabilidad": "Administrar\nInmediatamente",
    "ph": "6,5-8,5",
    "osmolaridad": "294-310",
    "riesgo": "Bajo",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 2.4,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: nefrotoxicidad y neurotoxicidad (parestesias, debilidad, bloqueo neuromuscular). Vigilar función renal y signos neurológicos."
  },
  {
    "id": 19,
    "nombre": "Daptomicina  500 mg",
    "categoria": "Antimicrobiano",
    "presentacion": "Daptomicina  500 mg",
    "reconstitucion": "10 mL \nSF 0.9%",
    "dilucion": "50 mL\n SF0.9%",
    "administracion": "IV: 30 min.",
    "estabilidad": "TA: 12 h\nRef.: 24 h",
    "ph": "4-5",
    "osmolaridad": "289-310",
    "riesgo": "Moderado",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 10.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: miopatía/elevación CPK, rabdomiólisis rara y neumonía eosinofílica. Vigilar CPK y dolor/debilidad muscular."
  },
  {
    "id": 20,
    "nombre": "Eritromicina  1g lactobionato",
    "categoria": "Antimicrobiano",
    "presentacion": "Eritromicina  1g lactobionato",
    "reconstitucion": "20 mL Agua para inyectables",
    "dilucion": "200 -1000 mL SF0.9%\n(1-5 mg/mL)",
    "administracion": "IV: 20-60 min",
    "estabilidad": "TA: 8 h\nRef.: 24 h",
    "ph": "7 (6,5-7,7)",
    "osmolaridad": "291",
    "riesgo": "Bajo",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 5.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: náuseas, flebitis, hepatotoxicidad colestásica, prolongación QT e interacciones. Vigilar ECG si riesgo de QT."
  },
  {
    "id": 21,
    "nombre": "Ertapenem  1 gr",
    "categoria": "Antimicrobiano",
    "presentacion": "Ertapenem  1 gr",
    "reconstitucion": "10 mL Agua para inyectables",
    "dilucion": "50 mL SF0.9%\n(20 mg/mL)",
    "administracion": "IV: 30 min",
    "estabilidad": "TA: 6 h\nRE.: 24 h",
    "ph": "7,5",
    "osmolaridad": "419",
    "riesgo": "Bajo",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 20.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: hipersensibilidad, diarrea/C. difficile, rash y convulsiones especialmente con falla renal o patología SNC. Ajustar a función renal."
  },
  {
    "id": 22,
    "nombre": "Fluconazol  400 mg/200 mL",
    "categoria": "Antimicrobiano",
    "presentacion": "Fluconazol  400 mg/200 mL",
    "reconstitucion": "No procede",
    "dilucion": "No procede",
    "administracion": "IV: 120 min",
    "estabilidad": "Uso inmediato",
    "ph": "4-8",
    "osmolaridad": "315",
    "riesgo": "Moderado",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": null,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: hepatotoxicidad, náuseas/rash, prolongación QT e interacciones farmacológicas. Vigilar pruebas hepáticas y fármacos concomitantes."
  },
  {
    "id": 23,
    "nombre": "Ganciclovir 500 mg",
    "categoria": "Antimicrobiano",
    "presentacion": "Ganciclovir 500 mg",
    "reconstitucion": "10 mL\nAgua para inyectables",
    "dilucion": "100 - 250 mL\n SF0.9%, SG 5%.\nNo exceder 10 mg/mL",
    "administracion": "IV: mínimo en 60 min",
    "estabilidad": "RE: 7 días\n 1-10 mg/mL en \nSF 0,9 % o SG 5 %",
    "ph": "11",
    "osmolaridad": "320",
    "riesgo": "Alto",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 10.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: neutropenia, anemia, trombocitopenia y toxicidad renal. Vigilar hemograma y función renal; ajustar según clearance."
  },
  {
    "id": 24,
    "nombre": "Gentamicina  80 mg",
    "categoria": "Antimicrobiano",
    "presentacion": "Gentamicina  80 mg",
    "reconstitucion": "No procede",
    "dilucion": "50-200 mL SF0.9%\nSG5%\nNo exceder 1 mg/mL",
    "administracion": "IV: 30-60 min",
    "estabilidad": "TA: 24 h",
    "ph": "3-5",
    "osmolaridad": "280-290",
    "riesgo": "Moderado",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 1.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: nefrotoxicidad, ototoxicidad y bloqueo neuromuscular raro. Vigilar función renal, audición y niveles plasmáticos si aplica."
  },
  {
    "id": 25,
    "nombre": "Imipenem cilastatina 500 mg",
    "categoria": "Antimicrobiano",
    "presentacion": "Imipenem cilastatina 500 mg",
    "reconstitucion": "10 mL \nSF 0.9%, SG5%",
    "dilucion": "500 mg en 100 mL 0.9% SG5%\n(5 mg/mL)",
    "administracion": "IV: 4 h",
    "estabilidad": "TA:4 h SG5%\nTA:10 h SF0.9%",
    "ph": "6,5-8,5",
    "osmolaridad": "368",
    "riesgo": "Moderado",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 5.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: hipersensibilidad, diarrea/C. difficile, rash y convulsiones especialmente con falla renal o patología SNC. Ajustar a función renal."
  },
  {
    "id": 26,
    "nombre": "Isoniazida  300 mg",
    "categoria": "Antimicrobiano",
    "presentacion": "Isoniazida  300 mg",
    "reconstitucion": "5 mL \nAgua para inyectable",
    "dilucion": "20-50 mL SF0.9%, SG5%",
    "administracion": "Bolo: 10-15 min\nIV: 60 min",
    "estabilidad": "No disponible",
    "ph": "No disponible",
    "osmolaridad": "No \ndisponible",
    "riesgo": "Alto",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 15.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: hepatotoxicidad y neuropatía periférica. Vigilar pruebas hepáticas y considerar piridoxina según riesgo clínico."
  },
  {
    "id": 27,
    "nombre": "Levofloxacino  500 mg",
    "categoria": "Antimicrobiano",
    "presentacion": "Levofloxacino  500 mg",
    "reconstitucion": "No procede",
    "dilucion": "No procede",
    "administracion": "IV 500 mg: 60 min4\nIV 750 mg: 90 min",
    "estabilidad": "Uso inmediato",
    "ph": "3,8-5,8",
    "osmolaridad": "250",
    "riesgo": "Bajo",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": null,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: prolongación QT, tendinopatía/ruptura tendinosa, alteraciones SNC, disglucemias y flebitis. Precaución en adulto mayor y falla renal."
  },
  {
    "id": 28,
    "nombre": "Linezolid  600 mg/300 mL",
    "categoria": "Antimicrobiano",
    "presentacion": "Linezolid  600 mg/300 mL",
    "reconstitucion": "No procede",
    "dilucion": "No procede",
    "administracion": "IV: 30-120 min",
    "estabilidad": "Uso inmediato",
    "ph": "4,8",
    "osmolaridad": "290",
    "riesgo": "Moderado",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": null,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: trombocitopenia/mielosupresión, neuropatía con uso prolongado, acidosis láctica e interacción serotoninérgica. Vigilar hemograma y fármacos serotoninérgicos."
  },
  {
    "id": 29,
    "nombre": "Metronidazol 500 mg/100 mL",
    "categoria": "Antimicrobiano",
    "presentacion": "Metronidazol 500 mg/100 mL",
    "reconstitucion": "No procede",
    "dilucion": "No procede",
    "administracion": "IV: 30-60 min",
    "estabilidad": "Uso inmediato",
    "ph": "5-7,0",
    "osmolaridad": "310",
    "riesgo": "Moderado",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": null,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: náuseas, sabor metálico, neuropatía periférica con uso prolongado y reacción tipo disulfiram con alcohol. Vigilar síntomas neurológicos."
  },
  {
    "id": 30,
    "nombre": "Meropenem  500 mg,  1000 mg",
    "categoria": "Antimicrobiano",
    "presentacion": "Meropenem  500 mg,  1000 mg",
    "reconstitucion": "10-20 mL\nAgua para inyectables",
    "dilucion": "500 mg en 100 mL9 SF 0.9%\n1 g en 200 mL SF 0.9%\n(5 -50 mg/mL)",
    "administracion": "IV: 15-30 min SG5%\nIV: 1-3 h SF 0.9%",
    "estabilidad": "Inmediatamente SG5%\n1-3 h en SF 0.9%",
    "ph": "7,3-8,3",
    "osmolaridad": "300",
    "riesgo": "Bajo",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 50.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: hipersensibilidad, diarrea/C. difficile, rash y convulsiones especialmente con falla renal o patología SNC. Ajustar a función renal."
  },
  {
    "id": 31,
    "nombre": "Penicilina sódica 1 millón y  2 millones UI",
    "categoria": "Antimicrobiano",
    "presentacion": "Penicilina sódica 1 millón y  2 millones UI",
    "reconstitucion": "5 mL\n Agua para inyectables",
    "dilucion": "50-1000 mL SF0.9%\n(100 millón UI/mL)",
    "administracion": "IV directa: 5 min\nIV:15-30 min",
    "estabilidad": "TA: 24 h",
    "ph": "6-8,5",
    "osmolaridad": "420",
    "riesgo": "Moderado",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": null,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: hipersensibilidad/anafilaxia, rash, diarrea/C. difficile y flebitis. Vigilar antecedentes de alergia beta-lactámica y sitio de infusión."
  },
  {
    "id": 32,
    "nombre": "Piperacilina-tazobactam 4.5 g",
    "categoria": "Antimicrobiano",
    "presentacion": "Piperacilina-tazobactam 4.5 g",
    "reconstitucion": "20 mL\nSF 0.9%\nAgua para inyectables",
    "dilucion": "50-100 mL\nSG 5%",
    "administracion": "4 h",
    "estabilidad": "TA: 12 h",
    "ph": "5,1-5,4",
    "osmolaridad": "445",
    "riesgo": "Moderado",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 90.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: hipersensibilidad, diarrea/C. difficile, alteraciones hematológicas, carga de sodio y nefrotoxicidad asociada a otros fármacos. Vigilar función renal."
  },
  {
    "id": 33,
    "nombre": "Rifampicina  600 mg",
    "categoria": "Antimicrobiano",
    "presentacion": "Rifampicina  600 mg",
    "reconstitucion": "10 mL\n Agua para inyectables",
    "dilucion": "100 mL SF0.9%, SG5%\n500 mL SF0.9%, SG5% (VVP)\nNo exceda 6 mg/mL",
    "administracion": "CVC: 30 min \nVVP: 2-3 h",
    "estabilidad": "TA:6 h SF 0.9%\nTA: 8 h SG5%",
    "ph": "No disponible",
    "osmolaridad": "No disponible",
    "riesgo": "Alto",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 6.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: hepatotoxicidad, molestias gastrointestinales, trombocitopenia rara, múltiples interacciones y coloración naranja de secreciones. Vigilar pruebas hepáticas."
  },
  {
    "id": 34,
    "nombre": "Sulfametoxazol-Trimetoprim  400/80 MG  AM (5 ML)",
    "categoria": "Antimicrobiano",
    "presentacion": "Sulfametoxazol-Trimetoprim  400/80 MG  AM (5 ML)",
    "reconstitucion": "No procede",
    "dilucion": "SF0.9% SG5%\n1 AM (5ML): 125 mL\n2 AM (10 ML): 250 mL\n3 AM (15ML):500 mL",
    "administracion": "IV: 30-90 min",
    "estabilidad": "TA: 6 h",
    "ph": "10",
    "osmolaridad": "541",
    "riesgo": "Alto",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": null,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: rash grave/SJS-TEN, hiperpotasemia, nefrotoxicidad, citopenias y alergia a sulfas. Vigilar K+, creatinina, piel y hemograma."
  },
  {
    "id": 35,
    "nombre": "Tigeciclina  50 mg",
    "categoria": "Antimicrobiano",
    "presentacion": "Tigeciclina  50 mg",
    "reconstitucion": "5.3 mL\nSF 0.9%, SG 5%",
    "dilucion": "100 mL \nSF 0.9%, SG 5%",
    "administracion": "IV: 30-60 min",
    "estabilidad": "TA: 6 h",
    "ph": "5,3",
    "osmolaridad": "270-281",
    "riesgo": "Bajo",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 0.5,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: náuseas/vómitos, hepatotoxicidad, pancreatitis rara y alteraciones de coagulación. Vigilar tolerancia digestiva y pruebas hepáticas."
  },
  {
    "id": 36,
    "nombre": "Vancomicina 500 mg 1000 mg",
    "categoria": "Antimicrobiano",
    "presentacion": "Vancomicina 500 mg 1000 mg",
    "reconstitucion": "20 mL\nAgua para inyectables",
    "dilucion": "1 g en 100-200 mL\nSF 0.9%, SG 5%\nNo exceder 5 mg/mL\nRestricción volumen: 10mg/mL",
    "administracion": "No exceder 10mg/min",
    "estabilidad": "RE: 24 h",
    "ph": "2,5-4,5",
    "osmolaridad": "290",
    "riesgo": "Alto",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 5.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: nefrotoxicidad, ototoxicidad rara, neutropenia y reacción por infusión de vancomicina. Vigilar creatinina, velocidad de infusión y sitio de punción."
  },
  {
    "id": 37,
    "nombre": "Voriconazol 200 mg",
    "categoria": "Antimicrobiano",
    "presentacion": "Voriconazol 200 mg",
    "reconstitucion": "20 mL\nAgua para inyectables",
    "dilucion": "100-250 mL\nSF 0.9%, SG5%",
    "administracion": "IV: 60-120 min\n (3 mg/kg/h)",
    "estabilidad": "RE: 24 h",
    "ph": "6-7",
    "osmolaridad": "No disponible",
    "riesgo": "Medio",
    "observaciones": "",
    "dosis": "",
    "maxMgMl": 2.0,
    "calculadora": "antimicrobiano",
    "ram": "RAM/precauciones: alteraciones visuales, hepatotoxicidad, rash/fotosensibilidad, alucinaciones y prolongación QT. Vigilar pruebas hepáticas, piel y ECG si corresponde."
  },
  {
    "id": 38,
    "nombre": "Atracurio",
    "categoria": "Sedoanalgesia",
    "presentacion": "Atracurio",
    "reconstitucion": "",
    "dilucion": "CVC: hasta 5mg/1ml(500 mg/100 ml)\nVVP: hasta 2.5 mg/1ml (250mg/100   ml)",
    "administracion": "EV directa: SI\nEV intermitente: SI\nEV continua: SI",
    "estabilidad": "24 hrs a temperatura ambiente",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "No clasificado",
    "observaciones": "Estabilidad según solvente: una solución de 0,5mg/mL es estable por 8 h en SG5% y 24 hr en SF 0,9%",
    "dosis": "Bolos: 0,4-0,5 mg/kg.\nIntermitente: 0,08-0,1mg/kg  \nc/20-45 min.\nContinua: 5-15 μg/kg/min",
    "solventes": "S.F 0.9%\nS.G 5%",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: liberación de histamina, hipotensión, broncoespasmo y bloqueo neuromuscular prolongado. Requiere monitorización ventilatoria."
  },
  {
    "id": 39,
    "nombre": "Bromuro de rocuronio",
    "categoria": "Sedoanalgesia",
    "presentacion": "Bromuro de rocuronio",
    "reconstitucion": "",
    "dilucion": "0,5 - 2 mg/ml",
    "administracion": "EV directa: SI\nEV intermitente: NO\nEV continua: SI\nIM: SI\nOtras vías: NO",
    "estabilidad": "24 horas a temperatura ambiente y expuestos a la luz ambiental",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "No clasificado",
    "observaciones": "Este medicamento no debe mezclarse con otros medicamentos\nReducir la dosis en función del peso corporal magro en pacientes obesos",
    "dosis": "5-15 μg/kg/min",
    "solventes": "S.F 0.9%\nSG 5%\nSRL",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: bloqueo neuromuscular prolongado, anafilaxia rara y debilidad residual. Requiere ventilación y monitorización del bloqueo."
  },
  {
    "id": 40,
    "nombre": "Dexmedetomidina",
    "categoria": "Sedoanalgesia",
    "presentacion": "Dexmedetomidina",
    "reconstitucion": "",
    "dilucion": "-1000 μg/250CC\n-Frasco viene   400μg en 100ml",
    "administracion": "EV directa: NO\nEV intermitente: NO\nEV continua: SI",
    "estabilidad": "24 horas a temperatura ambiente y expuestos a la luz ambiental",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "No clasificado",
    "observaciones": "Este medicamento puede provocar bradicardia e hipotensión. No deprime la respiración.\nNo administrar en bolo",
    "dosis": "0,4 a 1,4 μg/kg/Hr",
    "solventes": "S.F 0.9%\nS.G 5%\nSRL",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: bradicardia, hipotensión o hipertensión transitoria. Vigilar FC, PA y evitar bolo."
  },
  {
    "id": 41,
    "nombre": "Diazepam",
    "categoria": "Sedoanalgesia",
    "presentacion": "Diazepam",
    "reconstitucion": "",
    "dilucion": "No es recomendado\nSe puede diluir 1mg/ml",
    "administracion": "EV directa: SI\nEV intermitente: NO\nEV continua: SI\nIM: SI\nOtras vías: V.O., V.R",
    "estabilidad": "6 Hrs a Temperatura ambiente si esta diluido.\nProteger de la luz.",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "No clasificado",
    "observaciones": "Flumazenil invierte el efecto de benzodiacepinas en caso de sobredosis, no se recomienda Infusión Continua, debido a la precipitación de líquidos.",
    "dosis": "0,1 - 0,4 mg/kg/dosis.\nDosis máxima 20 mg/dosis",
    "solventes": "SF 0.9%\nSG 5%",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: depresión respiratoria, hipotensión, sedación excesiva, delirium/paradoja y dependencia con uso prolongado. Vigilar escala de sedación y ventilación."
  },
  {
    "id": 42,
    "nombre": "Etomidato",
    "categoria": "Sedoanalgesia",
    "presentacion": "Etomidato",
    "reconstitucion": "",
    "dilucion": "No diluir",
    "administracion": "EV directa: SI\nEV intermitente: NO\nEV continua: NO",
    "estabilidad": "Usar inmediatamente después de abrir",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "No clasificado",
    "observaciones": "No usar en dosis prolongadas.\nAlto riesgo de flebitis tras su uso.\nPoco o nulo efecto hemodinamico",
    "dosis": "0,2 a 0,3 mg/Kg\nAdministrar en 30-60 segundos",
    "solventes": "No diluir",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: mioclonías, dolor a la inyección, náuseas y supresión adrenal. Evitar uso prolongado."
  },
  {
    "id": 43,
    "nombre": "Fentanilo",
    "categoria": "Sedoanalgesia",
    "presentacion": "Fentanilo",
    "reconstitucion": "",
    "dilucion": "2000μg/100ml\n(2mg/100ml)\n4000 μg/100ml\n(4mg/100ml)",
    "administracion": "EV directa: SI\nEV intermitente: SI\nEV continua: SI\nIM: SI\nOtras vías: parche intradérmico",
    "estabilidad": "Temperatura ambiente.\n24 hrs",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "No clasificado",
    "observaciones": "La sobredosis es revertida con Naloxona",
    "dosis": "0.5-4.0 μg/Kg/Hr",
    "solventes": "SF 0.9%\nSG 5%",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: depresión respiratoria, bradicardia, náuseas/íleo y rigidez torácica con administración rápida. Vigilar ventilación y sedación."
  },
  {
    "id": 44,
    "nombre": "Flumazenil",
    "categoria": "Sedoanalgesia",
    "presentacion": "Flumazenil",
    "reconstitucion": "",
    "dilucion": "Bolo: No diluir\nIntermitente: 0.5mg/50ml",
    "administracion": "EV directa: SI\nEV intermitente: NO\nEV continua: SI\nIM: NO\nOtras vías: NO",
    "estabilidad": "Temperatura ambiente\nProteger de la luz.",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "No clasificado",
    "observaciones": "Se pueden presentar síntomas de deprivación en pacientes en\ntratamiento prolongado con benzodiacepinas. En este caso, adm 5mg de Midazolam vía IV lenta",
    "dosis": "Reducción de sedación inducida por benzodiacepinas:\nDosis inicial: 0.2mg c/15 Seg. Seguida de intervalos de 1min por dosis de 0.1-0.2mg de ser necesario.\nDosis usual: 0.3-0.6mg.\nSobredosis por benzodiacepinas: 0.2mg IV en 30seg. De ser necesario, dosis adicional de 0.3mg a los 30seg, a intervalos de 1min, dosis de 0.5mg, hasta una dosis total de 3-5mg",
    "solventes": "SF 0.9%\nSG 5%",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: convulsiones, agitación y síndrome de abstinencia en usuarios crónicos de benzodiacepinas. Usar con cautela."
  },
  {
    "id": 45,
    "nombre": "Haloperidol",
    "categoria": "Sedoanalgesia",
    "presentacion": "Haloperidol",
    "reconstitucion": "",
    "dilucion": "Bolo: No diluir\nInfusión intermitente: 5-10 mg en 100 ml.\nInfusión continua: 50 mg en 50 ml",
    "administracion": "IM: SI\nEV directa: SI\nEV intermitente: SI\nEV continua: SI",
    "estabilidad": "24 Hrs a Temperatura ambiente en SG5%.\n8 Hrs a Temperatura Ambiente en SF",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "No clasificado",
    "observaciones": "Puede generar hipotensión por excesiva sedación.",
    "dosis": "Agitación y Psicosis Aguda: dosis inicial de 2-10 mg IM (Máx. inicial 18 mg), se puede administrar cada 4-8 Hrs. Pacientes con disturbios severos podrían requerir dosis sobre 30 mg, seguidos de dosis de 5 mg. Antiemético: 0.5-2 mg/día (IM)",
    "solventes": "SF 0.9%\nSG 5%",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: prolongación QT, extrapiramidalismo, sedación/hipotensión y síndrome neuroléptico maligno raro. Vigilar ECG si riesgo."
  },
  {
    "id": 46,
    "nombre": "Ketamina",
    "categoria": "Sedoanalgesia",
    "presentacion": "Ketamina",
    "reconstitucion": "",
    "dilucion": "Infusión continua: 1G/250ml\nConcentración máxima de 4mg/1ml",
    "administracion": "IM: SI\nEV directa: SI\nEV intermitente: SI\nEV continua: SI",
    "estabilidad": "24 hrs a temperatura ambiente",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "No clasificado",
    "observaciones": "Para reducir la incidencia de reacciones al despertar, se administra Diazepam u otra benzodiacepina antes de la intervención o como adyuvante de la Ketamina",
    "dosis": "5-30 μg/kg/min",
    "solventes": "SF 0.9%\nSG 5%",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: hipertensión, taquicardia, hipersalivación, náuseas y fenómenos de emergencia/disociación. Vigilar PA, FC y secreciones."
  },
  {
    "id": 47,
    "nombre": "Ketoprofeno",
    "categoria": "Sedoanalgesia",
    "presentacion": "Ketoprofeno",
    "reconstitucion": "",
    "dilucion": "Bolo: 1ml en 10ml \nInfusión: 10ml en 500ml",
    "administracion": "EV directa: NO\nEV intermitente: SI\nEV continua: NO\nIM: SI\nOtras vías: V.O.",
    "estabilidad": "En suero fisiológico 24 horas.",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "No clasificado",
    "observaciones": "La administración directa (en bolo) puede provocar flebitis y dolor en sitio de inyección, es muy venoirritante.\nReduce o revierte los efectos de muchos antihipertensivos",
    "dosis": "100-300 mg/día\n20 – 30 minutos",
    "solventes": "SF 0.9%\nSG 5%\nSRL",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: sangrado digestivo, daño renal, broncoespasmo en susceptibles y dolor/flebitis local. Evitar o vigilar estrechamente en falla renal."
  },
  {
    "id": 48,
    "nombre": "Ketorolaco",
    "categoria": "Sedoanalgesia",
    "presentacion": "Ketorolaco",
    "reconstitucion": "",
    "dilucion": "En 50-100 ml\nConcentración máxima de 6 mg/ml.",
    "administracion": "IM: SI\nEV directa: SI\nEV continua: SI\nEV intermitente: NO",
    "estabilidad": "Estable por 48 horas.\nProtegido de la luz",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "No clasificado",
    "observaciones": "30mg de ketorolaco equivalen a 12 mg de morfina o meperidina.\nUtilizar con precaución en pacientes con daño renal o falla\nhepática.",
    "dosis": "IM: 60 mg, en una dosis o 30 mg cada 6 Hrs.\nIV: 30 mg, una dosis o 30 mg cada 6 Hrs.\nPaciente crítico (IM, IV): 30 mg una vez, seguido de 15-30 mg cada 6 Hrs, durante un máximo de 5 días.",
    "solventes": "SF 0.9%\nSG 5%",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: sangrado digestivo, daño renal, broncoespasmo en susceptibles y dolor/flebitis local. Evitar o vigilar estrechamente en falla renal."
  },
  {
    "id": 49,
    "nombre": "Lorazepam",
    "categoria": "Sedoanalgesia",
    "presentacion": "Lorazepam",
    "reconstitucion": "",
    "dilucion": "Diluir solo en caso de infusión continua\n1mg/1ml",
    "administracion": "EV directa: si\nEV intermitente: no\nEV continua: si\nIM: SI\nOtras vías: V.O.",
    "estabilidad": "Estable por 24 hrs a temperatura ambiente",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "No clasificado",
    "observaciones": "Puede causar: paro cardíaco, hipotensión, bradicardia, colapso cardiovascular, confusión, disnea, ataxia, amnesia, flebitis, dolor en el sitio de inyección, visión borrosa o doble, depresión respiratoria, laringoespasmo y, con uso prolongado, dependencia física.",
    "dosis": "Ansiedad: 1-4 mg.\nInsomnio asociado con ansiedad: 1-2 mg\nPre-medicación para anestesia:\nIM: 0,05 mg/Kg, administrado 2 Hrs antes de la cirugía (máximo 4 mg).\nIV: 0,044 mg/Kg administrado 15-20 min antes de la cirugía (dosis usual: 2 mg, máximo 4 mg).\nEstado Epiléptico:\nIV: 4 mg administrados lentamente (máximo 4mg/min), se puede repetir la dosis dentro de 5-10 min.\nIM: se puede utilizar, pero se prefiere IV.\nAgitación en UCI:\ndosis de carga 0,02-0,04 mg/Kg (dosis máxima 2 mg)\nDosis de mantención: 0,02-0,06 mg/Kg/2-6 Hrs. Según sea necesario, o 0,01-0,1 mg/Kg/Hr.; dosis máxima 10 mg/Hr.\nDelirio por abstinencia de alcohol: IM, IV: dosis fija, 2 mg cada 6 Hrs, durante 4 dosis, luego 1m cada 6 Hrs. Durante 8 dosis adicionales.",
    "solventes": "SF 0.9%\nSG 5%\nSRL",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: depresión respiratoria, hipotensión, sedación excesiva, delirium/paradoja y dependencia con uso prolongado. Vigilar escala de sedación y ventilación."
  },
  {
    "id": 50,
    "nombre": "Metamizol",
    "categoria": "Sedoanalgesia",
    "presentacion": "Metamizol",
    "reconstitucion": "",
    "dilucion": "Bolo: 0.5g en 5cc\nInfusión intermitente:\ndiluir en 50-100ml",
    "administracion": "EV directa: NO\nEV intermitente: SI\nEV continua: SI\nIM: SI\nOtras vías: VO, VR (supositorio)",
    "estabilidad": "Se protege de la luz en infusiones continuas de 24 horas",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "No clasificado",
    "observaciones": "Se puede administrar la ampolla de metamizol EV vía oral para\nmanejar el dolor",
    "dosis": "1-3 g/ 8 Hrs\nDosis máxima 4g en 24hrs.",
    "solventes": "SF 0.9\nSG 5%",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: hipotensión con administración rápida, reacciones alérgicas y agranulocitosis rara. Vigilar PA y signos de infección."
  },
  {
    "id": 51,
    "nombre": "Midazolam",
    "categoria": "Sedoanalgesia",
    "presentacion": "Midazolam",
    "reconstitucion": "",
    "dilucion": "100mg/100ml\no concentración máxima de 5mg/1ml",
    "administracion": "EV directa: SI\nEV infusión intermitente: NO\nEV infusión continua: SI\nIM: SI\nOtras vías: V.O., endotraqueal",
    "estabilidad": "Diluida: 24 horas.",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "No clasificado",
    "observaciones": "El antagonista es el Flumazenil.",
    "dosis": "Dosis de mantención: 0.015mg/kg/hr a 0.35mg/kg/hr",
    "solventes": "SF 0.9%\nSG 5%",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: depresión respiratoria, hipotensión, sedación excesiva, delirium/paradoja y dependencia con uso prolongado. Vigilar escala de sedación y ventilación."
  },
  {
    "id": 52,
    "nombre": "Morfina",
    "categoria": "Sedoanalgesia",
    "presentacion": "Morfina",
    "reconstitucion": "",
    "dilucion": "Bolo: 2.5 -15mg diluido en 5 o 10ml\nInfusión intermitente: 100mg por 100ml (1mg/ml). Rango: 0.1-1mg/ml\nInfusión continua: 100mg/50ml (2mg/ml) o en un rango 0.5-5mg/ml en caso de concentrar volumen",
    "administracion": "EV directa: SI\nEV intermitente: NO\nEV continua: SI\nIM: SI\nOtras vías: S.C.",
    "estabilidad": "A temperatura ambiente máximo 72 hrs.",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "No clasificado",
    "observaciones": "precaución en pacientes con pancreatitis (causa espasmo del esfínter de Oddi). Naloxona es antagonista",
    "dosis": "Las dosis y los intervalos de dosificación deben titularse para el alivio del dolor / prevención. 10mg (rango: 5-20mg) cada 4Hr IM o SC, o 2.5-15mg cada 4Hrs IV.\nDespués de la dosis de carga (15mg o más), adm una infusión continua de 0.8-80mg (hasta 150mg) por Hr",
    "solventes": "SF 0.9%\nSG 5%",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: depresión respiratoria, hipotensión, náuseas/íleo y sedación. Petidina: riesgo de neurotoxicidad/convulsiones por normeperidina."
  },
  {
    "id": 53,
    "nombre": "Naloxona",
    "categoria": "Sedoanalgesia",
    "presentacion": "Naloxona",
    "reconstitucion": "",
    "dilucion": "Bolo: 400μg por 1ml\nInfusión continua: 2mg en 50ml (40μg/ml) o 2mg en 500ml",
    "administracion": "EV directa: SI\nEV intermitente: NO\nEV continua: SI\nIM: SI\nOtras vías:S.C., intraoseo",
    "estabilidad": "Estable 24 horas en suero fisiológico o suero glucosado al 5%",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "No clasificado",
    "observaciones": "El fármaco revierte los efectos de los analgésicos narcóticos, por lo\ntanto se debe considerar administrar analgésicos no opioides para\nel tratamiento del dolor",
    "dosis": "Contrarrestar sedación: 2 mcg/kg/dosis, repetir después de 2\nminutos.\nAntagonismo morfina: 10 mcg/kg/dosis (Max. 0,4 mg).",
    "solventes": "SF 0.9%\nSG 5%",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: síndrome de abstinencia agudo, dolor, náuseas, hipertensión/taquicardia. Titular según respuesta clínica."
  },
  {
    "id": 54,
    "nombre": "Petidina",
    "categoria": "Sedoanalgesia",
    "presentacion": "Petidina",
    "reconstitucion": "",
    "dilucion": "Infusión intermitente: diluir en 50-100ml para obtener la concentración de 1mg/ml\nBolo: máximo 10 mg/ml\nInfusión continua: 50 mg por 50 ml (1mg/ml)",
    "administracion": "EV directa: SI\nEV intermitente: SI\nEV continua: SI\nIM: SI\nOtras vías: S.C.",
    "estabilidad": "Es estable por 7 días a temperatura ambiente y 14 días\nrefrigerada.",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "No clasificado",
    "observaciones": "La administración rápida puede producir un incremento en el riesgo\nde efectos adversos, principalmente depresión respiratoria, apnea,\nhipotensión",
    "dosis": "E.V: 0,5 - 1 mg/kg.\nI.M: 0,5 - 2 mg/kg.\nInfusion continua: 5 mg/kg en 50 ml, 1 - 4 ml/hr (0,1 - 0,4 mg/kg/hr).",
    "solventes": "SF 0.9%\nSG 5%",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: depresión respiratoria, hipotensión, náuseas/íleo y sedación. Petidina: riesgo de neurotoxicidad/convulsiones por normeperidina."
  },
  {
    "id": 55,
    "nombre": "Propofol",
    "categoria": "Sedoanalgesia",
    "presentacion": "Propofol",
    "reconstitucion": "",
    "dilucion": "---------------------------",
    "administracion": "EV directa: SI\nEV intermitente: NO\nEV continua: SI\nIM: NO\nOtras vías: NO",
    "estabilidad": "--------",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "No clasificado",
    "observaciones": "Agitar antes de usar, utilizar venas de calibre grande\nCambiar bajadas de bomba cada 24 hrs.\nNo mezclar con productos sanguíneos ni con otros medicamentos\npor la misma vía o en una mezcla.",
    "dosis": "Sedación: 1 - 3 mg/kg/hr (max 4mg/kg/hr), no más de 48 hr.\nCorto periodo de anestesia: 2,5 – 3,5 mg/kg, luego 7,5 – 15 mg/kg/hr.",
    "solventes": "----------------",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: hipotensión, depresión respiratoria, hipertrigliceridemia, infección por emulsión y síndrome de infusión de propofol en dosis altas/prolongadas."
  },
  {
    "id": 56,
    "nombre": "Succinilcolina",
    "categoria": "Sedoanalgesia",
    "presentacion": "Succinilcolina",
    "reconstitucion": "",
    "dilucion": "Bolo: no diluir \n1 - 2 mg/ml (infusión continua).",
    "administracion": "EV directa: SI\nEV intermitente: NO\nEV continua: SI (no recomendado)\nIM: SI\nOtras vías: NO",
    "estabilidad": "24 Hrs Refrigerado",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "No clasificado",
    "observaciones": "A 1 - 2 mg/ml en suero fisiológico es estable por 7 días a\ntemperatura ambiente y 4 semanas refrigerado.\nSin embargo, el proveedor recomienda no almacenar más allá\nde 24 horas el fármaco diluido, a temperatura ambiente (por\nestabilidad microbiológica)",
    "dosis": "Inicialmente 20 a 100mg IV. Alternativamente, 0.3 a 1.1mg/Kg.\nLa dosis puede ser repetida.\nSi no se puede acceder a la vía IV, administrar 2.5mg/Kg/dosis, IM",
    "solventes": "SF 0.9%\nSG 5%",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: hiperpotasemia, bradicardia, fasciculaciones, aumento de presión intraocular/gástrica y riesgo de hipertermia maligna."
  },
  {
    "id": 57,
    "nombre": "Esketamina",
    "categoria": "Sedoanalgesia",
    "presentacion": "Esketamina",
    "reconstitucion": "",
    "dilucion": "1mg/1ml",
    "administracion": "EV directa: SI\nEV intermitente: NO\nEV continua: SI",
    "estabilidad": "24 Hrs Refrigerado",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "No clasificado",
    "observaciones": "Puede aumentar frecuencia cardiaca y presión arterial.\nPuede generar disociación.\nPuede aumentar secreción bronquial",
    "dosis": "0,1-0,3 mg/kg/Hr",
    "solventes": "SF 0.9%\nSG 5%\nSRL",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: hipertensión, taquicardia, hipersalivación, náuseas y fenómenos de emergencia/disociación. Vigilar PA, FC y secreciones."
  },
  {
    "id": 58,
    "nombre": "Vecuronio",
    "categoria": "Sedoanalgesia",
    "presentacion": "Vecuronio",
    "reconstitucion": "",
    "dilucion": "CVC:(50 mg/50 mL)\nVVP: 20 mg/100 mL",
    "administracion": "Directa: Sí\nIntermitente: Sí\nContinua: Sí",
    "estabilidad": "24 Hrs Refrigerado",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "No clasificado",
    "observaciones": "Evitar su uso en pacientes con daño renal debido a que se prolonga el tiempo del bloqueo neuromuscular.",
    "dosis": "Dosis de carga o inducción: 0,08-0,1 mg/kg \nDosis de mantención: 0,8-1,2 mcg/kg/min",
    "solventes": "S.F 0.9%\nS.G 5%",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: bloqueo neuromuscular prolongado, anafilaxia rara y debilidad residual. Requiere ventilación y monitorización del bloqueo."
  },
  {
    "id": 59,
    "nombre": "Adrenalina",
    "categoria": "Vasoactiva",
    "presentacion": "Adrenalina",
    "reconstitucion": "",
    "dilucion": "10mg/100cc",
    "administracion": "Infusión continua / 0,01-1 μg/Kg/min",
    "estabilidad": "24 horas a temperatura ambiente",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "Alto",
    "observaciones": "Preparación fija según tabla institucional. No requiere calculadora de preparación.",
    "dosis": "0,01-1 μg/Kg/min",
    "solventes": "S.F 0.9%\nS.G 5%",
    "indicacion": "μg/Kg/min",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: taquiarritmias, hipertensión, isquemia, hiperglicemia y necrosis por extravasación. Usar bomba y vigilancia hemodinámica."
  },
  {
    "id": 60,
    "nombre": "Noradrenalina",
    "categoria": "Vasoactiva",
    "presentacion": "Noradrenalina",
    "reconstitucion": "",
    "dilucion": "4mg/250cc\n8mg/250cc\n16mg/250cc\n32mg/250cc",
    "administracion": "Infusión continua / 0,01-2 μg/Kg/min",
    "estabilidad": "24 horas a temperatura ambiente",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "Alto",
    "observaciones": "Preparación fija según tabla institucional. No requiere calculadora de preparación.",
    "dosis": "0,01-2 μg/Kg/min",
    "solventes": "S.F 0.9%\nS.G 5%",
    "indicacion": "μg/Kg/min",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: taquiarritmias, hipertensión, isquemia, hiperglicemia y necrosis por extravasación. Usar bomba y vigilancia hemodinámica."
  },
  {
    "id": 61,
    "nombre": "Dobutamina",
    "categoria": "Vasoactiva",
    "presentacion": "Dobutamina",
    "reconstitucion": "",
    "dilucion": "500mg/125cc\n500mg/250cc",
    "administracion": "Infusión continua / 0,5-20 μg/Kg/min",
    "estabilidad": "24 horas a temperatura ambiente",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "Alto",
    "observaciones": "Preparación fija según tabla institucional. No requiere calculadora de preparación.",
    "dosis": "0,5-20 μg/Kg/min",
    "solventes": "S.F 0.9%\nS.G 5%",
    "indicacion": "μg/Kg/min",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: taquicardia, arritmias, hipotensión o hipertensión y dolor torácico/isquemia. Vigilar ECG y PA."
  },
  {
    "id": 62,
    "nombre": "Milrinona",
    "categoria": "Vasoactiva",
    "presentacion": "Milrinona",
    "reconstitucion": "",
    "dilucion": "20mg/125cc\n20mg/250cc",
    "administracion": "Infusión continua / 0,125-0,75 μg/Kg/min",
    "estabilidad": "24 horas a temperatura ambiente",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "Alto",
    "observaciones": "Preparación fija según tabla institucional. No requiere calculadora de preparación.",
    "dosis": "0,125-0,75 μg/Kg/min",
    "solventes": "S.F 0.9%\nS.G 5%",
    "indicacion": "μg/Kg/min",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: hipotensión, arritmias y trombocitopenia. Ajustar en falla renal y vigilar PA/ECG."
  },
  {
    "id": 63,
    "nombre": "Dopamina",
    "categoria": "Vasoactiva",
    "presentacion": "Dopamina",
    "reconstitucion": "",
    "dilucion": "400mg/125cc\n400mg/250cc",
    "administracion": "Infusión continua / 2-50 μg/Kg/min",
    "estabilidad": "24 horas a temperatura ambiente",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "Alto",
    "observaciones": "Preparación fija según tabla institucional. No requiere calculadora de preparación.",
    "dosis": "2-50 μg/Kg/min",
    "solventes": "S.F 0.9%\nS.G 5%",
    "indicacion": "μg/Kg/min",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: taquiarritmias, hipertensión, náuseas e isquemia/necrosis por extravasación. Vigilar ECG, PA y sitio de infusión."
  },
  {
    "id": 64,
    "nombre": "Amiodarona",
    "categoria": "Vasoactiva",
    "presentacion": "Amiodarona",
    "reconstitucion": "",
    "dilucion": "600mg/250cc\nDepende de indicación medica",
    "administracion": "Infusión continua / Bolo: 50, 100, 150mg administrar en 10-15min en mínimo 50cc de suero\nResto de dosis se administra en 24 hrs en infusión continua,",
    "estabilidad": "24 horas a temperatura ambiente",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "Alto",
    "observaciones": "Preparación fija según tabla institucional. No requiere calculadora de preparación.",
    "dosis": "Bolo: 50, 100, 150mg administrar en 10-15min en mínimo 50cc de suero\nResto de dosis se administra en 24 hrs en infusión continua,",
    "solventes": "S.F 0.9%\nS.G 5%",
    "indicacion": "Ml/hr",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: hipotensión, bradicardia, prolongación QT, flebitis y alteración hepática. Usar vía adecuada y vigilar ECG/PA."
  },
  {
    "id": 65,
    "nombre": "Isoproterenol",
    "categoria": "Vasoactiva",
    "presentacion": "Isoproterenol",
    "reconstitucion": "",
    "dilucion": "1mg/250cc",
    "administracion": "Infusión continua / 1-4 μg/min",
    "estabilidad": "24 horas a temperatura ambiente, es fotosensible",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "Alto",
    "observaciones": "Preparación fija según tabla institucional. No requiere calculadora de preparación.",
    "dosis": "1-4 μg/min",
    "solventes": "S.F 0.9%\nS.G 5%, hay laboratorios que recomiendan solo en SG 5%",
    "indicacion": "μg/min",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: taquiarritmias, palpitaciones, isquemia miocárdica e hipotensión. Vigilar ECG y PA."
  },
  {
    "id": 66,
    "nombre": "Nitroglicerina",
    "categoria": "Vasoactiva",
    "presentacion": "Nitroglicerina",
    "reconstitucion": "",
    "dilucion": "50mg/250cc",
    "administracion": "Infusión continua / 10-200 μg/ min",
    "estabilidad": "24 horas a temperatura ambiente, es fotosensible",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "Alto",
    "observaciones": "Preparación fija según tabla institucional. No requiere calculadora de preparación.",
    "dosis": "10-200 μg/ min",
    "solventes": "S.F 0.9%\nS.G 5%",
    "indicacion": "μg/min",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: cefalea, hipotensión, taquicardia refleja y tolerancia. Vigilar PA y respuesta clínica."
  },
  {
    "id": 67,
    "nombre": "Nitroprusiato de sodio",
    "categoria": "Vasoactiva",
    "presentacion": "Nitroprusiato de sodio",
    "reconstitucion": "",
    "dilucion": "50mg/250cc",
    "administracion": "Infusión continua / 0,05-8 μg/Kg/min",
    "estabilidad": "Seguir recomendación de fabricante",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "Alto",
    "observaciones": "Preparación fija según tabla institucional. No requiere calculadora de preparación.",
    "dosis": "0,05-8 μg/Kg/min",
    "solventes": "S.G 5%",
    "indicacion": "μg/Kg/min",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: hipotensión severa y toxicidad por cianuro/tiocianato, especialmente en falla renal/hepática o infusiones prolongadas. Proteger de la luz."
  },
  {
    "id": 68,
    "nombre": "Labetalol",
    "categoria": "Vasoactiva",
    "presentacion": "Labetalol",
    "reconstitucion": "",
    "dilucion": "1mg/1ml",
    "administracion": "Infusión continua / 0,5-3 mg/min",
    "estabilidad": "24 horas a temperatura ambiente",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "Alto",
    "observaciones": "Preparación fija según tabla institucional. No requiere calculadora de preparación.",
    "dosis": "0,5-3 mg/min",
    "solventes": "S.F 0.9%\nS.G 5%",
    "indicacion": "Mg/min",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: hipotensión, bradicardia, bloqueo AV y broncoespasmo. Vigilar PA, FC y contraindicaciones beta-bloqueo."
  },
  {
    "id": 69,
    "nombre": "Vasopresina",
    "categoria": "Vasoactiva",
    "presentacion": "Vasopresina",
    "reconstitucion": "",
    "dilucion": "40 UI/100cc",
    "administracion": "Infusión continua / 0,01 – 0,07 UI/min\n(No hay información sobre efectividad a dosis mayor)",
    "estabilidad": "24 horas a temperatura ambiente",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "Alto",
    "observaciones": "Preparación fija según tabla institucional. No requiere calculadora de preparación.",
    "dosis": "0,01 – 0,07 UI/min\n(No hay información sobre efectividad a dosis mayor)",
    "solventes": "S.F 0,9%\nS.G 5%",
    "indicacion": "UI/min",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: isquemia cutánea/mesentérica/coronaria, hiponatremia y arritmias. Vigilar perfusión, sodio y ECG."
  },
  {
    "id": 70,
    "nombre": "Urapidil",
    "categoria": "Vasoactiva",
    "presentacion": "Urapidil",
    "reconstitucion": "",
    "dilucion": "300mg/100cc",
    "administracion": "Infusión continua / 9-30 mg/Hr",
    "estabilidad": "24 horas a temperatura ambiente",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "Alto",
    "observaciones": "Preparación fija según tabla institucional. No requiere calculadora de preparación.",
    "dosis": "9-30 mg/Hr",
    "solventes": "S.F 0,9%\nS.G 5%",
    "indicacion": "mg/Hr",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: hipotensión, mareos, náuseas, cefalea y taquicardia. Vigilar PA durante titulación."
  },
  {
    "id": 71,
    "nombre": "Heparina",
    "categoria": "Alto riesgo",
    "presentacion": "Heparina",
    "reconstitucion": "",
    "dilucion": "25000 UI/250ml",
    "administracion": "Dosis optima es aquella capaz de alargar ttpa entre 1,5 a 2,5 veces los valores normales del pcte",
    "estabilidad": "24 horas a temperatura ambiente",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "Alto",
    "observaciones": "Medicamento de alto riesgo. Preparación fija según tabla institucional.",
    "dosis": "Dosis optima es aquella capaz de alargar ttpa entre 1,5 a 2,5 veces los valores normales del pcte",
    "solventes": "S.F 0.9%",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: sangrado y trombocitopenia inducida por heparina. Vigilar TTPA/anti-Xa según protocolo, plaquetas y signos de sangrado."
  },
  {
    "id": 72,
    "nombre": "Insulina cristalina",
    "categoria": "Alto riesgo",
    "presentacion": "Insulina cristalina",
    "reconstitucion": "",
    "dilucion": "100 UI/ 100ml",
    "administracion": "Dosis optima es aquella que logra normalizar valores de glicemia en sangre",
    "estabilidad": "12 horas a temperatura ambiente",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "Alto",
    "observaciones": "Medicamento de alto riesgo. Preparación fija según tabla institucional.",
    "dosis": "Dosis optima es aquella que logra normalizar valores de glicemia en sangre",
    "solventes": "S.F 0.9%",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: hipoglicemia e hipokalemia. Control glicémico frecuente y vigilar potasio."
  },
  {
    "id": 73,
    "nombre": "Furosemida",
    "categoria": "Alto riesgo",
    "presentacion": "Furosemida",
    "reconstitucion": "",
    "dilucion": "100mg/100ml",
    "administracion": "5-30 mg/hr",
    "estabilidad": "24 horas a temperatura ambiente",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "Alto",
    "observaciones": "Medicamento de alto riesgo. Preparación fija según tabla institucional.",
    "dosis": "5-30 mg/hr",
    "solventes": "S.F 0.9%\nS.G 5%",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: hipokalemia, hipovolemia, hipotensión, daño renal prerrenal y ototoxicidad con dosis altas/rápidas. Vigilar diuresis, PA y electrolitos."
  },
  {
    "id": 74,
    "nombre": "Cloruro de potasio",
    "categoria": "Electrolito",
    "presentacion": "Cloruro de potasio",
    "reconstitucion": "",
    "dilucion": "-En S.F 0.9% o S.G 5%\n-Concentración máxima por VVP 3g por 1000ml de solución (40mEq por 1000ml) a una velocidad de infusión que no supere 0,5g hora por BIC.\n-Concentración máxima por CVC 3g Por 100ml de solución (4040mEq por 1000ml) a una velocidad de infusión que no supere 1g hora por BIC.",
    "administracion": "Nunca administrar medicamento en bolo.\nSe puede administrar como máximo 1,5g de KCl hora en hipocalemias severas, pero por un tiempo no mayor a 3 horas siempre y cuando el paciente este monitorizado.\nEn caso de administrar por VVP observar frecuentemente sitio de inserción y detener frente algún malestar del paciente.",
    "estabilidad": "Según preparación local",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "Alto",
    "observaciones": "Nunca administrar medicamento en bolo.\nSe puede administrar como máximo 1,5g de KCl hora en hipocalemias severas, pero por un tiempo no mayor a 3 horas siempre y cuando el paciente este monitorizado.\nEn caso de administrar por VVP observar frecuentemente sitio de inserción y detener frente algún malestar del paciente.",
    "dosis": "",
    "maxMgMl": null,
    "calculadora": "kcl",
    "ram": "RAM/precauciones: hiperpotasemia, arritmias, dolor/flebitis y necrosis por extravasación. Nunca en bolo; usar bomba y monitorización."
  },
  {
    "id": 75,
    "nombre": "Cloruro de sodio",
    "categoria": "Electrolito",
    "presentacion": "Cloruro de sodio",
    "reconstitucion": "",
    "dilucion": "Las diferentes concentraciones de NaCl se pueden preparar usando las ampollas de NaCl 10% con agua bidestilada o con soluciones de NaCl al 0.9%",
    "administracion": "Se puede administrar por VVP o por VVC.\nConcentraciones menores a 1.5% se pueden pasar por VVP.\nConcentraciones mayores se recomienda por VVC excepto en emergencias cuando hay hipertensión intracraneana donde se debe administrar bolos de NaCl al 3% o 10%",
    "estabilidad": "Según preparación local",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "Alto",
    "observaciones": "Se puede administrar por VVP o por VVC.\nConcentraciones menores a 1.5% se pueden pasar por VVP.\nConcentraciones mayores se recomienda por VVC excepto en emergencias cuando hay hipertensión intracraneana donde se debe administrar bolos de NaCl al 3% o 10%",
    "dosis": "",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: hipernatremia, sobrecarga de volumen, irritación venosa y riesgo de corrección rápida. Vigilar sodio, osmolaridad, balance y vía."
  },
  {
    "id": 76,
    "nombre": "Sulfato de magnesio",
    "categoria": "Electrolito",
    "presentacion": "Sulfato de magnesio",
    "reconstitucion": "",
    "dilucion": "Recomendado en S.F 0.9%\nPor VVP no mas de 1g por 20ml\nPara VVC concentración máxima \nDe 1g por 10ml\n(Recordar que ampolla al 25% \nContiene 1,25g de magnesio)",
    "administracion": "-Se puede administrar por VVP o VVC, en bolo, infusión intermitente o continua.\n-Bolo solo en emergencia asociada a hipomagnesemia severa en un tiempo de 1 a 5min\n-Infusión intermitente en 10 a 20 min no mas de una ampolla a la vez\n-Infusión continua de 0,1 a 1g/hr idealmente",
    "estabilidad": "Según preparación local",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "Alto",
    "observaciones": "-Se puede administrar por VVP o VVC, en bolo, infusión intermitente o continua.\n-Bolo solo en emergencia asociada a hipomagnesemia severa en un tiempo de 1 a 5min\n-Infusión intermitente en 10 a 20 min no mas de una ampolla a la vez\n-Infusión continua de 0,1 a 1g/hr idealmente",
    "dosis": "",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: hipotensión, rubor, bradicardia, hiporreflexia y depresión respiratoria si toxicidad. Vigilar reflejos, FR, PA y función renal."
  },
  {
    "id": 77,
    "nombre": "Gluconato de calcio",
    "categoria": "Electrolito",
    "presentacion": "Gluconato de calcio",
    "reconstitucion": "",
    "dilucion": "-En NaCl 0,9% y S.G 5% 1 ampolla en 50 a 100ml\n-Bolo en 20 a 50ml\n-Infusión continua o intermitente por VVP concentración máxima de 1g por 50ml\n-VVC concentración máxima de 1g en 20ml",
    "administracion": "-Por VVP o VVC.\n-En bolo se recomienda que se administre de manera lenta 3-5min, para evitar que una elevada concentración de Ca alcance el miocardio y pueda provocar un sincope cardiaco.\n-Pasar por vía exclusiva por riesgo de precipitar.",
    "estabilidad": "Según preparación local",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "Alto",
    "observaciones": "-Por VVP o VVC.\n-En bolo se recomienda que se administre de manera lenta 3-5min, para evitar que una elevada concentración de Ca alcance el miocardio y pueda provocar un sincope cardiaco.\n-Pasar por vía exclusiva por riesgo de precipitar.",
    "dosis": "",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: bradicardia/arritmias con administración rápida, flebitis y necrosis por extravasación. Administrar lento y por vía exclusiva."
  },
  {
    "id": 78,
    "nombre": "Fosfato monopotasico 15%\nBifosfato de potasio al 15%",
    "categoria": "Electrolito",
    "presentacion": "Fosfato monopotasico 15%\nBifosfato de potasio al 15%",
    "reconstitucion": "",
    "dilucion": "En NaCl al 0,9% o S.G al 5%\nVVP 1 ampolla en 250ml\nVVC 3 ampollas en 100ml",
    "administracion": "Por VVP o VVC en infusión intermitente o continua, nunca en bolo.\nVVP máximo 0,5g de bifosfato de potasio hora\nVVC máximo 1g de bifosfato de potasio hora",
    "estabilidad": "Según preparación local",
    "ph": "",
    "osmolaridad": "",
    "riesgo": "Alto",
    "observaciones": "Por VVP o VVC en infusión intermitente o continua, nunca en bolo.\nVVP máximo 0,5g de bifosfato de potasio hora\nVVC máximo 1g de bifosfato de potasio hora",
    "dosis": "",
    "maxMgMl": null,
    "calculadora": "no",
    "ram": "RAM/precauciones: hiperpotasemia, hipocalcemia, precipitación con calcio y flebitis. Vigilar K+, Ca/P y compatibilidades."
  }
];
const NACL_TABLES = {
  "En agua bidestilada": {
    "Volumen total de 250cc": [
      [
        "NaCl %",
        "Cantidad de Agua Bidestilada",
        "Cantidad de NaCl 10%",
        "Total de gramos NaCl en 250cc"
      ],
      [
        "7%",
        "75cc",
        "175cc",
        "17,5g"
      ],
      [
        "5%",
        "125cc",
        "125cc",
        "12,5g"
      ],
      [
        "3%",
        "175cc",
        "75cc",
        "7,5g"
      ],
      [
        "1.5%",
        "212,5cc",
        "37,5cc",
        "3,75g"
      ],
      [
        "0.45%",
        "238,75cc",
        "11,25cc",
        "1,125g"
      ]
    ],
    "Volumen total de 1000cc": [
      [
        "NaCl %",
        "Cantidad de Agua Bidestilada",
        "Cantidad de NaCl 10%",
        "Total de gramos NaCl en 1000cc"
      ],
      [
        "7%",
        "300cc",
        "700cc",
        "70g"
      ],
      [
        "5%",
        "500cc",
        "500cc",
        "50g"
      ],
      [
        "3%",
        "700cc",
        "300cc",
        "30g"
      ],
      [
        "1.5%",
        "850cc",
        "150cc",
        "15g"
      ],
      [
        "0.45%",
        "955cc",
        "45cc",
        "4,5g"
      ]
    ],
    "Volumen total de 500cc": [
      [
        "NaCl %",
        "Cantidad de Agua Bidestilada",
        "Cantidad de NaCl 10%",
        "Total de gramos NaCl en 500cc"
      ],
      [
        "7%",
        "150cc",
        "350cc",
        "35g"
      ],
      [
        "5%",
        "250cc",
        "250cc",
        "25g"
      ],
      [
        "3%",
        "350cc",
        "150cc",
        "15g"
      ],
      [
        "1.5%",
        "425cc",
        "75cc",
        "7,5g"
      ],
      [
        "0.45%",
        "477,5cc",
        "22,5cc",
        "2,25g"
      ]
    ]
  },
  "En NaCl 0,9%": {
    "Volumen total de 250cc": [
      [
        "NaCl %",
        "Cantidad NaCl al 0.9%",
        "Cantidad NaCl10%",
        "Total de gramos NaCl en 250cc"
      ],
      [
        "7%",
        "82cc",
        "168cc",
        "17,53g"
      ],
      [
        "5%",
        "137cc",
        "113cc",
        "12,53g"
      ],
      [
        "3%",
        "192cc",
        "58cc",
        "7,52g"
      ],
      [
        "1.5%",
        "233,5cc",
        "16,5cc",
        "3,75g"
      ],
      [
        "0.45%",
        "125cc",
        "125cc de agua bidestilada",
        "1,125g"
      ]
    ],
    "Volumen total de 500cc": [
      [
        "NaCl %",
        "Cantidad NaCl al 0.9%",
        "Cantidad NaCl10%",
        "Total de gramos NaCl en 500cc"
      ],
      [
        "7%",
        "165cc",
        "335cc",
        "34,98g"
      ],
      [
        "5%",
        "275cc",
        "225cc",
        "24,97g"
      ],
      [
        "3%",
        "385cc",
        "115cc",
        "14,96g"
      ],
      [
        "1.5%",
        "467cc",
        "33cc",
        "7,5g"
      ],
      [
        "0.45%",
        "250cc",
        "250cc de agua bidestilada",
        "2,25g"
      ]
    ],
    "Volumen total de 1000cc": [
      [
        "NaCl %",
        "Cantidad NaCl al 0.9%",
        "Cantidad NaCl10%",
        "Total de gramos NaCl en 1000cc"
      ],
      [
        "7%",
        "330cc",
        "670cc",
        "69.9g"
      ],
      [
        "5%",
        "550cc",
        "450cc",
        "49.9g"
      ],
      [
        "3%",
        "770cc",
        "230cc",
        "29.9g"
      ],
      [
        "1.5%",
        "935cc",
        "65cc",
        "14.9g"
      ],
      [
        "0.45%",
        "500cc",
        "500cc de agua bidestilada",
        "4.5g"
      ]
    ]
  }
};