-- Guía EV HCFB: registrar consultas anónimas
create table if not exists public.consultas_medicamentos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  medicamento_id text,
  medicamento text not null,
  categoria text,
  riesgo text,
  plataforma text,
  user_agent text
);

alter table public.consultas_medicamentos enable row level security;

drop policy if exists "insert consultas anonimas" on public.consultas_medicamentos;
create policy "insert consultas anonimas"
on public.consultas_medicamentos
for insert
to anon
with check (true);

drop policy if exists "leer consultas anonimas" on public.consultas_medicamentos;
create policy "leer consultas anonimas"
on public.consultas_medicamentos
for select
to anon
using (true);

create or replace function public.top_medicamentos(limite int default 8)
returns table(medicamento text, count bigint)
language sql
stable
as $$
  select cm.medicamento, count(*)::bigint
  from public.consultas_medicamentos cm
  group by cm.medicamento
  order by count(*) desc, cm.medicamento asc
  limit limite;
$$;
